name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_VERSION: 18.x

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Test
        run: pnpm run test || pnpm run test || pnpm run test || exit 1
        env:
          CI: true

      - name: Build
        run: pnpm run build
        env:
          CI: true

      - name: Lint
        run: pnpm lint
        env:
          CI: true
